#!/usr/bin/env python3
"""
Humanitarian risk modeling prototype.

Consumes data/dataset_integrado.csv generated by osint_pipeline.py and builds:
- a spatial grid,
- aggregated multimodal features,
- a dynamic Humanitarian Risk Index,
- weak future-risk labels,
- a Random Forest baseline,
- an adjacency graph for spatial/GNN extensions.

This script is intentionally defensive. It can run with the current CSV-first
project structure and does not require PostGIS for the local prototype.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.impute import SimpleImputer
from sklearn.metrics import classification_report, roc_auc_score
from sklearn.model_selection import train_test_split
from sklearn.neighbors import NearestNeighbors
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import RobustScaler

try:
    import geopandas as gpd
    from shapely.geometry import box
except ImportError as exc:  # pragma: no cover - user-facing dependency guard
    raise SystemExit(
        "This script requires geopandas and shapely. Install optional geospatial "
        "dependencies before running humanitarian risk modeling."
    ) from exc

try:
    import networkx as nx
except ImportError as exc:  # pragma: no cover
    raise SystemExit("This script requires networkx.") from exc


@dataclass
class RiskConfig:
    data_path: Path = Path("data/dataset_integrado.csv")
    output_dir: Path = Path("outputs/humanitarian_risk")
    crs: str = "EPSG:4326"
    grid_size_degrees: float = 0.75
    max_history_days: int = 60
    label_horizon_days: int = 7
    risk_threshold_quantile: float = 0.75


def robust_sigmoid_score(series: pd.Series) -> pd.Series:
    """Robustly scales a signal and maps it to [0, 1]."""

    values = pd.to_numeric(series, errors="coerce").fillna(0.0)
    iqr = values.quantile(0.75) - values.quantile(0.25)
    scaled = (values - values.median()) / (iqr + 1e-6)
    return 1.0 / (1.0 + np.exp(-scaled.clip(-20, 20)))


def load_events(config: RiskConfig) -> gpd.GeoDataFrame:
    """Loads normalized OSINT/geospatial events as points."""

    if not config.data_path.exists():
        raise FileNotFoundError(f"Missing {config.data_path}. Run osint_pipeline.py first.")

    df = pd.read_csv(config.data_path)
    for column in ["timestamp", "lat", "lon", "value"]:
        if column not in df.columns:
            df[column] = pd.NA

    df["timestamp"] = pd.to_datetime(df["timestamp"], utc=True, errors="coerce")
    df["lat"] = pd.to_numeric(df["lat"], errors="coerce")
    df["lon"] = pd.to_numeric(df["lon"], errors="coerce")
    df["value"] = pd.to_numeric(df["value"], errors="coerce").fillna(1.0)
    df = df.dropna(subset=["timestamp", "lat", "lon"])
    df = df[df["lat"].between(-90, 90) & df["lon"].between(-180, 180)].copy()
    max_timestamp = df["timestamp"].max()
    min_timestamp = max_timestamp - pd.Timedelta(days=config.max_history_days)
    df = df[df["timestamp"] >= min_timestamp].copy()
    if df.empty:
        raise ValueError("No valid geospatial rows found in dataset_integrado.csv.")

    return gpd.GeoDataFrame(
        df,
        geometry=gpd.points_from_xy(df["lon"], df["lat"]),
        crs=config.crs,
    )


def build_grid(events: gpd.GeoDataFrame, grid_size: float) -> gpd.GeoDataFrame:
    """Builds a regular lon/lat grid covering the event extent."""

    minx, miny, maxx, maxy = events.total_bounds
    padding = grid_size
    xs = np.arange(minx - padding, maxx + padding + grid_size, grid_size)
    ys = np.arange(miny - padding, maxy + padding + grid_size, grid_size)

    rows = []
    for ix, x in enumerate(xs[:-1]):
        for iy, y in enumerate(ys[:-1]):
            rows.append(
                {
                    "grid_id": f"g_{ix}_{iy}",
                    "geometry": box(x, y, x + grid_size, y + grid_size),
                }
            )
    return gpd.GeoDataFrame(rows, crs=events.crs)


def complete_grid_dates(features: pd.DataFrame, grid_ids: Iterable[str]) -> pd.DataFrame:
    """Ensures all grid/date combinations exist for rolling windows."""

    if features.empty:
        return features
    dates = pd.date_range(features["date"].min(), features["date"].max(), freq="D", tz="UTC")
    index = pd.MultiIndex.from_product([list(grid_ids), dates], names=["grid_id", "date"])
    return (
        features.set_index(["grid_id", "date"])
        .reindex(index, fill_value=0)
        .reset_index()
    )


def aggregate_features(events: gpd.GeoDataFrame, grid: gpd.GeoDataFrame) -> pd.DataFrame:
    """Aggregates multimodal sources by grid cell and day."""

    joined = gpd.sjoin(events, grid[["grid_id", "geometry"]], predicate="within", how="inner")
    if joined.empty:
        raise ValueError("No events fell inside the generated grid.")

    joined["date"] = joined["timestamp"].dt.floor("D")
    joined["source"] = joined["source"].fillna("unknown").astype(str)
    grouped = (
        joined.groupby(["grid_id", "date", "source"])
        .agg(event_count=("source", "size"), value_sum=("value", "sum"))
        .reset_index()
    )
    pivot = grouped.pivot_table(
        index=["grid_id", "date"],
        columns="source",
        values=["event_count", "value_sum"],
        aggfunc="sum",
        fill_value=0,
    )
    pivot.columns = ["_".join(map(str, col)).strip() for col in pivot.columns]
    features = pivot.reset_index()
    active_grid_ids = sorted(features["grid_id"].dropna().unique())
    features = complete_grid_dates(features, active_grid_ids)

    numeric_cols = [c for c in features.columns if c not in {"grid_id", "date"}]
    features[numeric_cols] = features[numeric_cols].apply(pd.to_numeric, errors="coerce").fillna(0.0)

    for col in numeric_cols:
        features[f"{col}_7d"] = (
            features.sort_values("date")
            .groupby("grid_id")[col]
            .transform(lambda s: s.rolling(7, min_periods=1).sum())
        )
    return features


def add_humanitarian_risk_index(features: pd.DataFrame) -> pd.DataFrame:
    """Computes a transparent multimodal Humanitarian Risk Index."""

    features = features.copy()
    component_map = {
        "conflict": ["event_count_acled_7d", "value_sum_acled_7d"],
        "thermal": ["event_count_nasa_firms_7d", "value_sum_nasa_firms_7d"],
        "mobility": ["event_count_opensky_7d", "value_sum_opensky_7d"],
        "media": [
            "event_count_gdelt_7d",
            "event_count_google_news_rss_7d",
            "event_count_bbc_rss_7d",
            "event_count_aljazeera_rss_7d",
        ],
        "humanitarian": ["event_count_unhcr_7d", "event_count_hdx_7d", "event_count_worldpop_7d"],
        "infrastructure": ["event_count_openstreetmap_7d", "event_count_sentinel_hub_7d"],
    }

    component_scores = []
    for name, columns in component_map.items():
        valid = [col for col in columns if col in features.columns]
        raw = features[valid].sum(axis=1) if valid else pd.Series(0.0, index=features.index)
        features[f"hri_{name}"] = robust_sigmoid_score(raw)
        component_scores.append(features[f"hri_{name}"])

    features["humanitarian_risk_index"] = pd.concat(component_scores, axis=1).mean(axis=1)
    return features


def add_future_risk_labels(features: pd.DataFrame, config: RiskConfig) -> pd.DataFrame:
    """Builds weak supervised labels from future HRI values."""

    features = features.sort_values(["grid_id", "date"]).copy()
    future = (
        features.groupby("grid_id")["humanitarian_risk_index"]
        .shift(-config.label_horizon_days)
        .fillna(features["humanitarian_risk_index"])
    )
    threshold = future.quantile(config.risk_threshold_quantile)
    features["future_hri"] = future
    features["risk_label"] = (future >= threshold).astype(int)
    if features["risk_label"].nunique() < 2 and len(features) > 1:
        ranked_future = future.rank(method="first", pct=True)
        features["risk_label"] = (ranked_future >= config.risk_threshold_quantile).astype(int)
    return features


def train_random_forest(features: pd.DataFrame) -> tuple[Pipeline, pd.DataFrame]:
    """Trains a Random Forest baseline and prints evaluation metrics."""

    exclude = {"grid_id", "date", "future_hri", "risk_label"}
    feature_cols = [col for col in features.columns if col not in exclude]
    X = features[feature_cols]
    y = features["risk_label"]

    stratify = y if y.nunique() > 1 and y.value_counts().min() >= 2 else None
    X_train, X_test, y_train, y_test = train_test_split(
        X,
        y,
        test_size=0.25,
        random_state=42,
        stratify=stratify,
    )
    model = Pipeline(
        steps=[
            ("imputer", SimpleImputer(strategy="median")),
            ("scaler", RobustScaler()),
            (
                "rf",
                RandomForestClassifier(
                    n_estimators=200,
                    min_samples_leaf=2,
                    class_weight="balanced",
                    random_state=42,
                    n_jobs=-1,
                ),
            ),
        ]
    )
    model.fit(X_train, y_train)
    preds = model.predict(X_test)
    print(classification_report(y_test, preds, zero_division=0))
    if y_test.nunique() > 1:
        proba = model.predict_proba(X_test)[:, 1]
        print(f"ROC AUC: {roc_auc_score(y_test, proba):.3f}")
    return model, X_test


def build_adjacency_graph(grid: gpd.GeoDataFrame) -> nx.Graph:
    """Builds a grid adjacency graph for spatial propagation or GNNs."""

    graph = nx.Graph()
    for _, row in grid.iterrows():
        graph.add_node(row["grid_id"])

    spatial_index = grid.sindex
    for idx, row in grid.iterrows():
        candidates = list(spatial_index.intersection(row.geometry.bounds))
        for candidate_idx in candidates:
            if idx >= candidate_idx:
                continue
            other = grid.iloc[candidate_idx]
            if row.geometry.touches(other.geometry) or row.geometry.intersects(other.geometry):
                graph.add_edge(row["grid_id"], other["grid_id"], weight=1.0)

    if graph.number_of_edges() == 0 and graph.number_of_nodes() > 1:
        bounds = grid.geometry.bounds
        coords = np.column_stack(
            [
                ((bounds["minx"] + bounds["maxx"]) / 2).to_numpy(),
                ((bounds["miny"] + bounds["maxy"]) / 2).to_numpy(),
            ]
        )
        neighbors = min(5, len(grid))
        nearest = NearestNeighbors(n_neighbors=neighbors, metric="euclidean")
        nearest.fit(coords)
        distances, indices = nearest.kneighbors(coords)
        grid_ids = grid["grid_id"].to_numpy()
        for row_idx, neighbor_indices in enumerate(indices):
            for distance, neighbor_idx in zip(distances[row_idx][1:], neighbor_indices[1:]):
                graph.add_edge(grid_ids[row_idx], grid_ids[neighbor_idx], weight=float(distance))
    return graph


def save_outputs(features: pd.DataFrame, graph: nx.Graph, config: RiskConfig) -> None:
    """Persists feature table and graph edge list."""

    config.output_dir.mkdir(parents=True, exist_ok=True)
    features.to_csv(config.output_dir / "humanitarian_risk_features.csv", index=False)
    nx.write_weighted_edgelist(graph, config.output_dir / "regional_adjacency.edgelist")
    print(f"Saved outputs in {config.output_dir}")


def main() -> None:
    config = RiskConfig()
    events = load_events(config)
    grid = build_grid(events, config.grid_size_degrees)
    features = aggregate_features(events, grid)
    features = add_humanitarian_risk_index(features)
    features = add_future_risk_labels(features, config)
    active_grid_ids = set(features["grid_id"].dropna().unique())
    active_grid = grid[grid["grid_id"].isin(active_grid_ids)].copy()
    graph = build_adjacency_graph(active_grid)
    save_outputs(features, graph, config)
    train_random_forest(features)
    print(f"Graph nodes={graph.number_of_nodes()} edges={graph.number_of_edges()}")


if __name__ == "__main__":
    main()
